name: CI

on:
  push:
    branches:
      - main
      - dev 

jobs:
  build-main:
    if: github.ref == 'refs/heads/main'
    runs-on: timetable-back
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Add yarn globally
        run: npm install --global yarn

      - name: Install dependencies
        run:  yarn install

      - name: Build and Test for Production
        run: |
          echo "Running production build"
          # sudo cp .env /home/user/timetable-back/
          yarn build

      - name: Deploy to Production
        run: |
          cp -a ~/timetable-back/actions-runner/_work/timetable-back/timetable-back/. /home/timetable-back/
          cd /home/timetable-back/
          sudo pm2 delete timetable-back
          sudo PORT=4455 pm2 start:prod --name timetable-back

